### ISSUE TITLE
How to keep the size of scratchpad terminal

### ISSUE THREAD

**Issue by ywpkwon** [V2BlockBuster2K/Awespuccin#3]
I really appreciate your setting and I'm learning a lot.
I noticed `super+s` gives me a scratchpad terminal. When I resize, hide and show, the terminal gets back to its original size. I'm new to AwesomeWM and Lua. Can you please give me some solution or advice?

**Comment by V2BlockBuster2K** [comment]
So the size gets resized if you hide or show because its hard coded into my config [here](https://github.com/V2BlockBuster2K/Awespuccin/blob/main/conf/awesome/ui/popups/scratchpad/init.lua) (line: geometry). It's safe possible to safe the Scratchpad size somehow, but I don't know it right away. The most similar thing to safeing the size of a client is probably [here](https://github.com/V2BlockBuster2K/Awespuccin/blob/main/conf/awesome/lib/savefloats.lua) (saves the floating size of a client) and remembers position.
